#version: "3"
#services:
#  ancestors-app:
#    image: ancestors-app
#    ports:
#      - "8080:8080"
#    networks:
#      - ancestors-mysql
#    depends_on:
#      - mysqldb
#
#  mysqldb:
#    image: mysql:8
#    networks:
#      - ancestors-mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=ancestors
#
#networks:
#  ancestors-mysql: